"""added dp03

Revision ID: 3036654156be
Revises: 230c180d3150
Create Date: 2025-01-20 08:47:09.241860

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3036654156be"
down_revision: Union[str, None] = "230c180d3150"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dp03table",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("geoid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("total_house", sa.Integer(), nullable=False),
        sa.Column("inc_less_10k", sa.Integer(), nullable=False),
        sa.Column("inc_10k_15k", sa.Integer(), nullable=False),
        sa.Column("inc_15_25k", sa.Integer(), nullable=False),
        sa.Column("inc_25k_35k", sa.Integer(), nullable=False),
        sa.Column("inc_35k_50k", sa.Integer(), nullable=False),
        sa.Column("inc_50k_75k", sa.Integer(), nullable=False),
        sa.Column("inc_75k_100k", sa.Integer(), nullable=False),
        sa.Column("inc_100k_150k", sa.Integer(), nullable=False),
        sa.Column("inc_150k_200k", sa.Integer(), nullable=False),
        sa.Column("inc_more_200k", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dp03table")
    # ### end Alembic commands ###
