"""added pumstable

Revision ID: 96a9d5c9cfae
Revises: 230c180d3150
Create Date: 2025-01-19 21:36:27.495330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96a9d5c9cfae'
down_revision: Union[str, None] = '230c180d3150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pumstable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('adjinc', sa.Float(), nullable=False),
    sa.Column('hincp', sa.Integer(), nullable=False),
    sa.Column('pwgtp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pumstable')
    # ### end Alembic commands ###
