"""initial migrations

Revision ID: 9c4d618dbd84
Revises: 
Create Date: 2025-01-14 20:09:10.497747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9c4d618dbd84'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("SELECT load_extension('mod_spatialite')")
    op.create_table('geotable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geoid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_geotable_geometry', 'geotable', ['geometry'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_geotable_geometry', table_name='geotable', postgresql_using='gist')
    op.drop_table('geotable')
    # ### end Alembic commands ###
